name: 更新数据并部署

on:
  schedule:
    # 每3小时执行一次
    - cron: '0 */3 * * *'
  push:
    branches: [main]  # 当推送到main分支时
  workflow_dispatch:  # 允许手动触发

# 设置权限
permissions:
  contents: read
  pages: write
  id-token: write

# 允许一个并发部署
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  update-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # === 数据更新部分 ===
      - name: 检出代码
        uses: actions/checkout@v4
        
      - name: 设置Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: 安装pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8.4.0
          
      - name: 安装依赖
        run: pnpm install
        
      - name: 更新RSS源数据
        run: node scripts/update-feeds.js
        env:
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
          LLM_API_BASE: ${{ secrets.LLM_API_BASE }}
          LLM_NAME: ${{ secrets.LLM_NAME }}
          
      # === 构建部署部分 ===
      - name: 构建项目
        run: pnpm build
      
      # 如果存在CNAME文件，确保它被复制到输出目录
      - name: 复制CNAME到输出目录
        run: |
          if [ -f "CNAME" ]; then
            cp CNAME ./out/
            echo "已复制CNAME文件到输出目录"
          else
            echo "未找到CNAME文件，跳过"
          fi
      
      - name: 设置Pages
        uses: actions/configure-pages@v4
      
      - name: 上传构建结果
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

      - name: 部署到GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 